name = "abbfel4"
author = "TechnicProblem"
version = "1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3df6caedecaf275ff21630c108bb50b124c5c9ec7106b6acc6e6e88bf7ac0d52"

[versions]
forge = "36.0.42"
minecraft = "1.16.5"
