name = "abbfel4"
author = "TechnicProblem"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "893faa4170e7e562c1c36890ba1d36ddc68834bd80c615502dd6ea87a6134243"

[versions]
forge = "36.0.42"
minecraft = "1.16.5"
