name = "abbfel4"
author = "TechnicProblem"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d618db099f2a3cb2adde0995e2d97613ebd18f3041dd9e83e154315edd3e82ad"

[versions]
forge = "36.0.42"
minecraft = "1.16.5"
