name = "Abnormals Core"
filename = "abnormals_core-1.16.4-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/757/abnormals_core-1.16.4-3.0.6.jar"
hash-format = "murmur2"
hash = "896203051"

[update]
[update.curseforge]
file-id = 3157757
project-id = 382216
release-channel = "beta"
