name = "AppleSkin"
filename = "AppleSkin-mc1.16.2-forge-1.0.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3035/787/AppleSkin-mc1.16.2-forge-1.0.14.jar"
hash-format = "murmur2"
hash = "4238944857"

[update]
[update.curseforge]
file-id = 3035787
project-id = 248787
release-channel = "beta"
