name = "Artifacts"
filename = "Artifacts-1.16.5-2.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3208/626/Artifacts-1.16.5-2.8.0.jar"
hash-format = "murmur2"
hash = "659795054"

[update]
[update.curseforge]
file-id = 3208626
project-id = 312353
release-channel = "beta"
