name = "BlockCarpentry"
filename = "blockcarpentry-1.16-0.3.5a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3147/183/blockcarpentry-1.16-0.3.5a.jar"
hash-format = "murmur2"
hash = "1343748634"

[update]
[update.curseforge]
file-id = 3147183
project-id = 401658
release-channel = "beta"
