name = "Bookshelf"
filename = "Bookshelf-1.16.5-10.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/154/Bookshelf-1.16.5-10.0.1.jar"
hash-format = "murmur2"
hash = "4049979082"

[update]
[update.curseforge]
file-id = 3170154
project-id = 228525
release-channel = "beta"
