name = "Botany Pots"
filename = "BotanyPots-1.16.5-7.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/920/BotanyPots-1.16.5-7.0.8.jar"
hash-format = "murmur2"
hash = "4292639887"

[update]
[update.curseforge]
file-id = 3198920
project-id = 353928
release-channel = "beta"
