name = "Botany Trees"
filename = "BotanyTrees-1.16.5-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/857/BotanyTrees-1.16.5-3.0.2.jar"
hash-format = "murmur2"
hash = "2463075517"

[update]
[update.curseforge]
file-id = 3198857
project-id = 411357
release-channel = "beta"
