name = "Botania"
filename = "Botania-1.16.4-411.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3175/663/Botania-1.16.4-411.jar"
hash-format = "murmur2"
hash = "2170884133"

[update]
[update.curseforge]
file-id = 3175663
project-id = 225643
release-channel = "beta"
