name = "CC: Tweaked"
filename = "cc-tweaked-1.16.4-1.95.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/424/cc-tweaked-1.16.4-1.95.2.jar"
hash-format = "murmur2"
hash = "910443070"

[update]
[update.curseforge]
file-id = 3170424
project-id = 282001
release-channel = "beta"
