name = "Cooking for Blockheads"
filename = "CookingForBlockheads_1.16.3-9.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3098/223/CookingForBlockheads_1.16.3-9.2.2.jar"
hash-format = "murmur2"
hash = "2729888061"

[update]
[update.curseforge]
file-id = 3098223
project-id = 231484
release-channel = "beta"
