name = "Curios API (Forge)"
filename = "curios-forge-1.16.5-4.0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3186/427/curios-forge-1.16.5-4.0.4.0.jar"
hash-format = "murmur2"
hash = "3219474219"

[update]
[update.curseforge]
file-id = 3186427
project-id = 309927
release-channel = "beta"
