name = "Curious Shulker Boxes (Forge)"
filename = "curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3175/855/curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar"
hash-format = "murmur2"
hash = "695847992"

[update]
[update.curseforge]
file-id = 3175855
project-id = 316881
release-channel = "beta"
