name = "Dark Utilities"
filename = "DarkUtilities-1.16.5-8.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/877/DarkUtilities-1.16.5-8.0.3.jar"
hash-format = "murmur2"
hash = "1144350438"

[update]
[update.curseforge]
file-id = 3198877
project-id = 242195
release-channel = "beta"
