name = "Decorative Blocks modded compat"
filename = "decorative_blocks_abnormals-1.16.4-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3163/81/decorative_blocks_abnormals-1.16.4-1.1.jar"
hash-format = "murmur2"
hash = "1394974810"

[update]
[update.curseforge]
file-id = 3163081
project-id = 421760
release-channel = "beta"
