name = "Enchanted Book Redesign"
filename = "enchantedbookredesign-3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3130/523/enchantedbookredesign-3.2.jar"
hash-format = "murmur2"
hash = "1832229376"

[update]
[update.curseforge]
file-id = 3130523
project-id = 348076
release-channel = "beta"
