name = "Farmer's Delight"
filename = "FarmersDelight-1.16.3-0.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3188/508/FarmersDelight-1.16.3-0.3.2.jar"
hash-format = "murmur2"
hash = "411674378"

[update]
[update.curseforge]
file-id = 3188508
project-id = 398521
release-channel = "beta"
