name = "FTB Teams"
filename = "ftb-teams-1604.1.0.15-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/798/ftb-teams-1604.1.0.15-forge.jar"
hash-format = "murmur2"
hash = "87278723"

[update]
[update.curseforge]
file-id = 3182798
project-id = 404468
release-channel = "beta"
