name = "GraveStone Mod"
filename = "gravestone-1.16.5-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3195/857/gravestone-1.16.5-1.0.1.jar"
hash-format = "murmur2"
hash = "601325149"

[update]
[update.curseforge]
file-id = 3195857
project-id = 238551
release-channel = "beta"
