name = "[FORGE] Iron Furnaces"
filename = "ironfurnaces-1.16.5-2.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3196/39/ironfurnaces-1.16.5-2.6.3.jar"
hash-format = "murmur2"
hash = "911430001"

[update]
[update.curseforge]
file-id = 3196039
project-id = 237664
release-channel = "beta"
