name = "Just Enough Items (JEI)"
filename = "jei-1.16.4-7.6.1.71.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3192/904/jei-1.16.4-7.6.1.71.jar"
hash-format = "murmur2"
hash = "2618392244"

[update]
[update.curseforge]
file-id = 3192904
project-id = 238222
release-channel = "beta"
