name = "Jumbo Furnace"
filename = "jumbofurnace-1.16.4-2.2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3120/970/jumbofurnace-1.16.4-2.2.0.1.jar"
hash-format = "murmur2"
hash = "2944756317"

[update]
[update.curseforge]
file-id = 3120970
project-id = 390880
release-channel = "beta"
