name = "Just Enough Resources (JER)"
filename = "JustEnoughResources-1.16.3-0.12.0.100.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/754/JustEnoughResources-1.16.3-0.12.0.100.jar"
hash-format = "murmur2"
hash = "2911312110"

[update]
[update.curseforge]
file-id = 3066754
project-id = 240630
release-channel = "beta"
