name = "Macaw's Paintings"
filename = "mcw-paintings-1.0.0-mc1.16.4-5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3174/820/mcw-paintings-1.0.0-mc1.16.4-5.jar"
hash-format = "murmur2"
hash = "378507295"

[update]
[update.curseforge]
file-id = 3174820
project-id = 438116
release-channel = "beta"
