name = "Macaw's Windows"
filename = "mcw-windows-1.0.3-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/515/mcw-windows-1.0.3-mc1.16.5.jar"
hash-format = "murmur2"
hash = "2057769744"

[update]
[update.curseforge]
file-id = 3200515
project-id = 363569
release-channel = "beta"
