name = "Macaw's Trapdoors"
filename = "mcw-trapdors-1.0.1-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/352/mcw-trapdors-1.0.1-mc1.16.5.jar"
hash-format = "murmur2"
hash = "1261360812"

[update]
[update.curseforge]
file-id = 3182352
project-id = 400933
release-channel = "beta"
