name = "Modular Routers"
filename = "modular-routers-1.16.4-7.3.1-50.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3176/107/modular-routers-1.16.4-7.3.1-50.jar"
hash-format = "murmur2"
hash = "3232893107"

[update]
[update.curseforge]
file-id = 3176107
project-id = 250294
release-channel = "beta"
