name = "More Red"
filename = "morered-1.16.4-2.0.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3184/810/morered-1.16.4-2.0.1.3.jar"
hash-format = "murmur2"
hash = "1402702411"

[update]
[update.curseforge]
file-id = 3184810
project-id = 387638
release-channel = "beta"
