name = "Pam's HarvestCraft 2 - Food Extended"
filename = "pamhc2foodextended-1.16.3-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3190/664/pamhc2foodextended-1.16.3-1.0.1.jar"
hash-format = "murmur2"
hash = "94959805"

[update]
[update.curseforge]
file-id = 3190664
project-id = 402231
release-channel = "beta"
