name = "Pam's HarvestCraft 2 - Trees"
filename = "pamhc2trees-1.16.3-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3117/43/pamhc2trees-1.16.3-1.0.0.jar"
hash-format = "murmur2"
hash = "1977795253"

[update]
[update.curseforge]
file-id = 3117043
project-id = 365460
release-channel = "beta"
