name = "Pickle Tweaks"
filename = "PickleTweaks-1.16.4-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3187/185/PickleTweaks-1.16.4-5.2.0.jar"
hash-format = "murmur2"
hash = "2161247520"

[update]
[update.curseforge]
file-id = 3187185
project-id = 238761
release-channel = "beta"
