name = "Simply Tea!"
filename = "simplytea-1.16.5-2.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3187/134/simplytea-1.16.5-2.3.4.jar"
hash-format = "murmur2"
hash = "241894990"

[update]
[update.curseforge]
file-id = 3187134
project-id = 268373
release-channel = "beta"
