name = "Useful Railroads"
filename = "useful_railroads-1.16.4-1.4.6.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3177/291/useful_railroads-1.16.4-1.4.6.35.jar"
hash-format = "murmur2"
hash = "1356937600"

[update]
[update.curseforge]
file-id = 3177291
project-id = 306475
release-channel = "beta"
