name = "Xaero's World Map"
filename = "XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/214/XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "2118083762"

[update]
[update.curseforge]
file-id = 3200214
project-id = 317780
release-channel = "beta"
